spring.application.name=PGDBFFDemo

logging.level.root=info
logging.level.com.fincons=debug

logging.file.name=./PGDBFFDemo.log
logging.pattern.console=  %d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\\(%F:%L\\) - %msg%n


server.port = 9071

spring.security.user.name=user
spring.security.user.password=pwd